version: '3.8'

services:
  php-web:
    image: php:7.4-apache
    container_name: php-web
    restart: always
    ports:
      - "85:80"
    volumes:
      - .:/var/www/html
    depends_on:
      php-mysql:
        condition: service_healthy
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile

  php-mysql:
    image: mysql:5.7
    container_name: php-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_alumni
      MYSQL_USER: alumni_user
      MYSQL_PASSWORD: alumni_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_alumni.sql:/docker-entrypoint-initdb.d/db_alumni.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:

volumes:
  mysql_data:

