apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web
  namespace: preprod
  labels:
    app: php-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-web
  template:
    metadata:
      labels:
        app: php-web
    spec:
      containers:
        - name: php-web
          image: web-alumni:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

